# Generated by Django 6.0.2 on 2026-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept_Details',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('HOD', models.CharField(max_length=100)),
                ('total_staff', models.IntegerField()),
                ('total_student', models.IntegerField()),
            ],
        ),
    ]
